import { sql } from '@payloadcms/db-postgres'
import type { MigrateUpArgs, MigrateDownArgs } from '@payloadcms/db-postgres'

/**
 * Products gains the marketing bands Pages already had — trust row, FAQ,
 * showcase, ticket form, video, archive — so a product page can carry the
 * content that used to need a second "Buy Now" landing page beside it.
 *
 * The tables are CLONED from their `pages_*` counterparts with
 * `LIKE ... INCLUDING ALL` rather than re-typed. Six block types across live
 * and version tables is ~50 columns of hand-copied DDL, and the last time a
 * migration in this repo enumerated block tables by hand it enumerated two of
 * six. Postgres already knows the shape; ask it. @see docs/FOOTGUNS.md
 *
 * LIKE copies columns, defaults, checks and indexes — but NOT foreign keys, so
 * each parent link is re-declared below. It also copies `serial` defaults
 * verbatim, which would leave the clone drawing ids from the SOURCE table's
 * sequence; every integer-id clone is switched to its own identity instead.
 */

/** [clone, source, parent table, parent column type] */
const TABLES: Array<[string, string, string, 'varchar' | 'integer']> = [
  // Live tables — block ids are varchar, parents are the collection row.
  ['products_blocks_archive', 'pages_blocks_archive', 'products', 'integer'],
  ['products_blocks_faq', 'pages_blocks_faq', 'products', 'integer'],
  ['products_blocks_faq_items', 'pages_blocks_faq_items', 'products_blocks_faq', 'varchar'],
  ['products_blocks_showcase', 'pages_blocks_showcase', 'products', 'integer'],
  [
    'products_blocks_showcase_items',
    'pages_blocks_showcase_items',
    'products_blocks_showcase',
    'varchar',
  ],
  ['products_blocks_ticket_form', 'pages_blocks_ticket_form', 'products', 'integer'],
  ['products_blocks_trust_row', 'pages_blocks_trust_row', 'products', 'integer'],
  [
    'products_blocks_trust_row_items',
    'pages_blocks_trust_row_items',
    'products_blocks_trust_row',
    'varchar',
  ],
  ['products_blocks_video', 'pages_blocks_video', 'products', 'integer'],
  // Version twins — block ids are serial, parents are the version row.
  ['_products_v_blocks_archive', '_pages_v_blocks_archive', '_products_v', 'integer'],
  ['_products_v_blocks_faq', '_pages_v_blocks_faq', '_products_v', 'integer'],
  [
    '_products_v_blocks_faq_items',
    '_pages_v_blocks_faq_items',
    '_products_v_blocks_faq',
    'integer',
  ],
  ['_products_v_blocks_showcase', '_pages_v_blocks_showcase', '_products_v', 'integer'],
  [
    '_products_v_blocks_showcase_items',
    '_pages_v_blocks_showcase_items',
    '_products_v_blocks_showcase',
    'integer',
  ],
  ['_products_v_blocks_ticket_form', '_pages_v_blocks_ticket_form', '_products_v', 'integer'],
  ['_products_v_blocks_trust_row', '_pages_v_blocks_trust_row', '_products_v', 'integer'],
  [
    '_products_v_blocks_trust_row_items',
    '_pages_v_blocks_trust_row_items',
    '_products_v_blocks_trust_row',
    'integer',
  ],
  ['_products_v_blocks_video', '_pages_v_blocks_video', '_products_v', 'integer'],
]

export async function up({ db }: MigrateUpArgs): Promise<void> {
  for (const [clone, source, parent] of TABLES) {
    await db.execute(
      sql.raw(`
        DO $$
        BEGIN
          IF to_regclass('public.${source}') IS NULL THEN RETURN; END IF;
          IF to_regclass('public.${clone}') IS NOT NULL THEN RETURN; END IF;

          EXECUTE 'CREATE TABLE "${clone}" (LIKE "${source}" INCLUDING ALL)';

          -- A cloned serial would keep drawing from the source table's sequence.
          IF EXISTS (
            SELECT 1 FROM information_schema.columns
            WHERE table_name = '${clone}' AND column_name = 'id'
              AND data_type = 'integer' AND column_default IS NOT NULL
          ) THEN
            EXECUTE 'ALTER TABLE "${clone}" ALTER COLUMN "id" DROP DEFAULT';
            EXECUTE 'ALTER TABLE "${clone}" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY';
          END IF;

          EXECUTE 'ALTER TABLE "${clone}" ADD CONSTRAINT "${clone}_parent_id_fk"
                   FOREIGN KEY ("_parent_id") REFERENCES "${parent}"("id") ON DELETE CASCADE';
        END $$;
      `),
    )
  }

  // A cloned enum column still points at the SOURCE table's type
  // (enum_pages_blocks_trust_row_items_icon on a products table). Payload's
  // generated schema expects the type named after the table it's on, so give
  // each cloned column its own type with the same labels. Driven off the
  // catalog rather than a list, so it stays right as blocks change.
  await db.execute(
    sql.raw(`
      DO $$
      DECLARE r RECORD; labels TEXT; wanted TEXT;
      BEGIN
        FOR r IN
          SELECT c.table_name, c.column_name, c.udt_name, c.column_default
          FROM information_schema.columns c
          WHERE c.table_schema = 'public'
            AND c.data_type = 'USER-DEFINED'
            AND (c.table_name LIKE 'products_blocks_%' OR c.table_name LIKE '\\_products\\_v\\_blocks\\_%')
            AND (c.udt_name LIKE 'enum\\_pages\\_%' OR c.udt_name LIKE 'enum\\_\\_pages\\_%')
        LOOP
          wanted := 'enum_' || r.table_name || '_' || r.column_name;

          IF to_regtype(quote_ident(wanted)) IS NULL THEN
            SELECT string_agg(quote_literal(e.enumlabel), ',' ORDER BY e.enumsortorder)
              INTO labels
              FROM pg_enum e JOIN pg_type t ON t.oid = e.enumtypid
             WHERE t.typname = r.udt_name;
            EXECUTE format('CREATE TYPE %I AS ENUM (%s)', wanted, labels);
          END IF;

          EXECUTE format(
            'ALTER TABLE %I ALTER COLUMN %I DROP DEFAULT, ALTER COLUMN %I TYPE %I USING %I::text::%I',
            r.table_name, r.column_name, r.column_name, wanted, r.column_name, wanted);

          -- Re-declare the default the retype had to drop, now in the new type.
          IF r.column_default IS NOT NULL THEN
            EXECUTE format('ALTER TABLE %I ALTER COLUMN %I SET DEFAULT %L::%I',
              r.table_name, r.column_name,
              substring(r.column_default from '^''(.*)''::'), wanted);
          END IF;
        END LOOP;
      END $$;
    `),
  )

  // The Archive block can now card Posts, not just Products — a new value on
  // every copy of that enum (pages, posts, products, and each version twin).
  await db.execute(
    sql.raw(`
      DO $$
      DECLARE t RECORD;
      BEGIN
        FOR t IN SELECT typname FROM pg_type WHERE typname LIKE 'enum%blocks_archive_relation_to' LOOP
          IF NOT EXISTS (
            SELECT 1 FROM pg_enum e JOIN pg_type ty ON ty.oid = e.enumtypid
            WHERE ty.typname = t.typname AND e.enumlabel = 'posts'
          ) THEN
            EXECUTE format('ALTER TYPE %I ADD VALUE %L', t.typname, 'posts');
          END IF;
        END LOOP;
      END $$;
    `),
  )

  // Media links the clone didn't inherit — a deleted image must null the field,
  // not block the delete or leave a dangling id.
  for (const [table, column] of [
    ['products_blocks_showcase_items', 'image_id'],
    ['products_blocks_video', 'media_id'],
    ['products_blocks_video', 'poster_id'],
    ['_products_v_blocks_showcase_items', 'image_id'],
    ['_products_v_blocks_video', 'media_id'],
    ['_products_v_blocks_video', 'poster_id'],
  ]) {
    await db.execute(
      sql.raw(`
        DO $$
        BEGIN
          IF to_regclass('public.${table}') IS NULL THEN RETURN; END IF;
          IF NOT EXISTS (
            SELECT 1 FROM information_schema.columns
            WHERE table_name = '${table}' AND column_name = '${column}'
          ) THEN RETURN; END IF;
          IF EXISTS (
            SELECT 1 FROM pg_constraint WHERE conname = '${table}_${column}_fkey'
          ) THEN RETURN; END IF;

          EXECUTE 'ALTER TABLE "${table}" ADD CONSTRAINT "${table}_${column}_fkey"
                   FOREIGN KEY ("${column}") REFERENCES "media"("id") ON DELETE SET NULL';
        END $$;
      `),
    )
  }
}

export async function down({ db }: MigrateDownArgs): Promise<void> {
  // Reverse order so item tables drop before the blocks that own them.
  for (const [clone] of [...TABLES].reverse()) {
    await db.execute(sql.raw(`DROP TABLE IF EXISTS "${clone}" CASCADE;`))
  }
}
