/**
 * ChatControl - Core types for Angel OS chat system.
 * Four modes: minimalist (floating bubble), single-channel, multi-channel (dashboard),
 * sidebar (dashboard right-panel LEO chat).
 */

export interface ChatMessage {
  id: string
  role: 'user' | 'leo' | 'system'
  content: string
  timestamp: Date
  authorName?: string
  /** True while SSE is still streaming this message's content */
  isStreaming?: boolean
  /** Active tool call name (shown as status indicator during data lookups) */
  activeToolCall?: string
  /** Images attached to or generated by this message */
  images?: Array<{
    url: string
    alt?: string
    mediaId?: number
  }>
  metadata?: {
    agentName?: string
    agentType?: string
    conversationId?: string
    messageType?: string
  }
}

export interface ChatChannel {
  id: string
  name: string
  slug: string
  description?: string
  type: string
  spaceId: string
  isDefault?: boolean
  unreadCount?: number
  /** Widget state storage (task lists, timelines, note hierarchies) */
  data?: Record<string, unknown> | null
  /** UI configuration (active widgets, layout, display preferences) */
  widgets?: Array<{ type: string; position: number; config: Record<string, unknown> }> | null
}

export interface ChatSpace {
  id: string
  name: string
  slug: string
  description?: string
  /** True for system-created spaces (e.g. AI Bus) */
  isSystem?: boolean
  /** Space visibility from Payload */
  visibility?: 'public' | 'invite_only' | 'private'
}

export type ChatMode = 'minimalist' | 'single-channel' | 'multi-channel' | 'sidebar'

export interface ChatControlProps {
  mode: ChatMode
  /** Tenant slug for API calls */
  tenantSlug?: string
  /** Space ID to scope channels/messages */
  spaceId?: string
  /** Pre-loaded spaces list (avoids client-side fetch when server has the data) */
  spaces?: ChatSpace[]
  /** Callback when user switches to a different space */
  onSpaceChange?: (spaceId: string) => void
  /** Channel slug for single-channel mode */
  channelSlug?: string
  /** Enable LiveKit audio/video in channel headers */
  liveKitEnabled?: boolean
  /** Position for minimalist floating bubble */
  position?: 'bottom-right' | 'bottom-left'
  /** Theme override */
  theme?: 'light' | 'dark' | 'auto'
  /** Class name for custom styling */
  className?: string
}
