/**
 * ChatControl - Core types for Angel OS chat system.
 * Four modes: minimalist (floating bubble), single-channel, multi-channel (dashboard),
 * sidebar (dashboard right-panel LEO chat).
 */

export interface ChatMessage {
  id: string
  role: 'user' | 'leo' | 'system'
  content: string
  timestamp: Date
  authorName?: string
  /** Author user id — lets the UI gate "edit your own message". */
  authorId?: string
  /** Source channel slug — surfaced in the space-level Catch-All view for triage/jump. */
  channel?: string
  /** True once the message has been edited (metadata.edited). */
  edited?: boolean
  /** Prior versions, newest last — the append-only revision log (metadata.revisions). */
  revisions?: Array<{ content: string; editedAt?: string; editedBy?: string | number | null; moderation?: boolean }>
  /** True once a moderator (non-author) has redacted/edited this message. */
  moderated?: boolean
  /** True while SSE is still streaming this message's content */
  isStreaming?: boolean
  /** Timestamp (ms) of the last SSE delta/tool_call event — drives the liveness indicator decay */
  lastDeltaAt?: number
  /** Active tool call name (shown as status indicator during data lookups) */
  activeToolCall?: string
  /** True when this message is from a deep-think (escalated model) round */
  isDeepThink?: boolean
  /** True when this message represents a failed turn (provider/tool error) */
  isError?: boolean
  /** Raw provider/tool error text, surfaced on hover + copyable */
  errorDetail?: string
  /** Images attached to or generated by this message */
  images?: Array<{
    url: string
    alt?: string
    mediaId?: number
  }>
  /** File attachments (non-image files) */
  attachments?: Array<{
    url: string
    filename: string
    mimeType?: string
    filesize?: number
    mediaId?: number
  }>
  metadata?: {
    agentName?: string
    agentType?: string
    conversationId?: string
    messageType?: string
  }
  /** UMS widget configurations (inline forms, cards, etc.) */
  widgets?: Array<{
    widgetType: string
    [key: string]: unknown
  }>
}

export interface ChatChannel {
  id: string
  name: string
  slug: string
  description?: string
  type: string
  spaceId: string
  isDefault?: boolean
  /**
   * Unread messages in this channel, already capped by the server (99 = "99+").
   * Populated by ChatProvider from /api/chat/unread; absent without a provider.
   * Was declared here and populated by nobody until 260824.
   */
  unreadCount?: number
  /** Explicit channel members (required for DMs, optional for regular channels) */
  members?: Array<{ id: string; name?: string; email?: string }>
  /** Channel source — native for in-app, or external bridge origin */
  source?: 'native' | 'whatsapp' | 'email' | 'google_chat' | 'sms'
  /** Widget state storage (task lists, timelines, note hierarchies) */
  data?: Record<string, unknown> | null
  /** UI configuration (active widgets, layout, display preferences) */
  widgets?: Array<{ type: string; position: number; config: Record<string, unknown> }> | null
}

export interface ChatSpace {
  id: string
  name: string
  slug: string
  description?: string
  /** True for system-created spaces (e.g. AI Bus) */
  isSystem?: boolean
  /** Space visibility from Payload */
  visibility?: 'public' | 'invite_only' | 'private'
  /** Enabled applet IDs for this space (default: ['chat', 'files', 'tasks']) */
  enabledApplets?: string[]
}

// ─── Applets ──────────────────────────────────────────────────────

export interface Applet {
  id: string
  label: string
  icon: string // Lucide icon name
  isDefault?: boolean
}

/** Registry of built-in applets. Future sprints swap placeholders for real components. */
export const DEFAULT_APPLETS: Applet[] = [
  { id: 'chat', label: 'Chat', icon: 'MessageSquare', isDefault: true },
  { id: 'voice', label: 'Voice', icon: 'Headphones' },
  { id: 'files', label: 'Files', icon: 'FolderOpen' },
  { id: 'tasks', label: 'Tasks', icon: 'CheckSquare' },
  { id: 'notes', label: 'Notes', icon: 'ListTree' },
  { id: 'book', label: 'Read', icon: 'BookOpen' },
]

export type ChatMode = 'minimalist' | 'single-channel' | 'multi-channel' | 'sidebar'

export interface ChatControlProps {
  mode: ChatMode
  /** Tenant slug for API calls */
  tenantSlug?: string
  /** Tenant ID for DM channel operations */
  tenantId?: string
  /** Current user ID */
  userId?: string
  /** Space ID to scope channels/messages */
  spaceId?: string
  /** DM system space ID (for persistent LEO DMs) */
  dmSpaceId?: string
  /** Pre-loaded spaces list (avoids client-side fetch when server has the data) */
  spaces?: ChatSpace[]
  /** Callback when user switches to a different space */
  onSpaceChange?: (spaceId: string) => void
  /** Channel slug for single-channel mode */
  channelSlug?: string
  /** Enable LiveKit audio/video in channel headers */
  liveKitEnabled?: boolean
  /** Position for minimalist floating bubble */
  position?: 'bottom-right' | 'bottom-left'
  /** Theme override */
  theme?: 'light' | 'dark' | 'auto'
  /** Class name for custom styling */
  className?: string
}
